"""empty message

Revision ID: 288817a457b8
Revises: 
Create Date: 2025-05-06 11:26:43.918148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288817a457b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index('ix_organizations_admin_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_constraint('users_organization_id_fkey', type_='foreignkey')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_organization_id_fkey', 'organizations', ['organization_id'], ['id'])
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index('ix_organizations_admin_id', ['admin_id'], unique=False)

    # ### end Alembic commands ###
