"""kitchenstation and orderstatus added

Revision ID: 470b1670e09a
Revises: 51c61ceb7185
Create Date: 2025-05-13 17:01:58.675918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470b1670e09a'
down_revision = '51c61ceb7185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prep_instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('station_assignment_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('station_assignment_time')
        batch_op.drop_column('priority')
        batch_op.drop_column('prep_instructions')

    # ### end Alembic commands ###
