"""Add kitchen_station_id to orders

Revision ID: 650e3023e9d1
Revises: 470b1670e09a
Create Date: 2025-05-14 12:25:05.620555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650e3023e9d1'
down_revision = '470b1670e09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kitchen_station_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'kitchen_stations', ['kitchen_station_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('kitchen_station_id')

    # ### end Alembic commands ###
