"""changes to order model

Revision ID: bb742492aea9
Revises: f07124bb69bb
Create Date: 2025-05-19 11:45:26.274260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb742492aea9'
down_revision = 'f07124bb69bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('on_hold_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('on_hold_at')
        batch_op.drop_column('rejected_at')

    # ### end Alembic commands ###
