"""Changed table schema

Revision ID: 49ae5dc36e7c
Revises: 7563aa229634
Create Date: 2025-05-08 10:26:43.882443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ae5dc36e7c'
down_revision = '7563aa229634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_url', sa.String(length=500), nullable=True))
        batch_op.drop_constraint('tables_qr_code_key', type_='unique')
        batch_op.drop_column('qr_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('tables_qr_code_key', ['qr_code'])
        batch_op.drop_column('qr_code_url')

    # ### end Alembic commands ###
