"""order model update

Revision ID: 51c61ceb7185
Revises: 72b2bdd152db
Create Date: 2025-05-12 15:31:52.677872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c61ceb7185'
down_revision = '72b2bdd152db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('preparing_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ready_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('served_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('special_requests', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('special_requests')
        batch_op.drop_column('served_at')
        batch_op.drop_column('ready_at')
        batch_op.drop_column('preparing_at')
        batch_op.drop_column('accepted_at')

    # ### end Alembic commands ###
