"""Initial migration from existing schema

Revision ID: bd36fb4397d3
Revises: 
Create Date: 2025-10-16 10:54:55.070112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd36fb4397d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kitchen_stations')
    op.drop_table('daily_specials')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_kitchen_station_id_fkey', type_='foreignkey')
        batch_op.drop_column('kitchen_station_id')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_4', sa.String(length=255), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('image_4')
        batch_op.drop_column('image_3')
        batch_op.drop_column('image_2')
        batch_op.drop_column('image_1')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kitchen_station_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('orders_kitchen_station_id_fkey', 'kitchen_stations', ['kitchen_station_id'], ['id'])

    op.create_table('daily_specials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('menu_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name='daily_specials_menu_item_id_fkey'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='daily_specials_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='daily_specials_pkey'),
    sa.UniqueConstraint('menu_item_id', name='daily_specials_menu_item_id_key'),
    sa.UniqueConstraint('organization_id', name='daily_specials_organization_id_key')
    )
    op.create_table('kitchen_stations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='kitchen_stations_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='kitchen_stations_pkey')
    )
    # ### end Alembic commands ###
