"""Add image columns to Organization model

Revision ID: c7be3bd4a4cd
Revises: bd36fb4397d3
Create Date: 2025-10-16 15:07:35.060566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7be3bd4a4cd'
down_revision = 'bd36fb4397d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_4', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('image_4')
        batch_op.drop_column('image_3')
        batch_op.drop_column('image_2')
        batch_op.drop_column('image_1')

    # ### end Alembic commands ###
