"""Recreate migrations

Revision ID: db9f1aa03d73
Revises: 8462294a77d7
Create Date: 2025-06-06 11:41:36.130385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9f1aa03d73'
down_revision = '8462294a77d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image4', sa.String(length=255), nullable=True))



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kitchen_station_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('orders_kitchen_station_id_fkey', 'kitchen_stations', ['kitchen_station_id'], ['id'])

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('image4')
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')
        batch_op.drop_column('image1')

    op.create_table('kitchen_stations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='kitchen_stations_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='kitchen_stations_pkey')
    )
    # ### end Alembic commands ###
